name: Build Frontend Web

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'DeckOfCardsWeb/**'
      - '.github/workflows/build-frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'DeckOfCardsWeb/**'
      - '.github/workflows/build-frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore DeckOfCardsWeb/DeckOfCardsWeb.csproj
      
    - name: Build
      run: dotnet build DeckOfCardsWeb/DeckOfCardsWeb.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test DeckOfCardsWeb/DeckOfCardsWeb.csproj --no-build --configuration Release --verbosity normal