name: Run Tests
permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'deck-of-cards-api/**'
      - 'deck-of-cards-test/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'deck-of-cards-api/**'
      - 'deck-of-cards-test/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore if-tester.sln
      
    - name: Build API
      run: dotnet build deck-of-cards-api/deck-of-cards-api.csproj --no-restore --configuration Release
      
    - name: Build tests
      run: dotnet build deck-of-cards-test/deck-of-cards-test.csproj --no-restore --configuration Release
      
    - name: Run unit and integration tests
      run: dotnet test deck-of-cards-test/deck-of-cards-test.csproj --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: always()
      with:
        files: '**/coverage.cobertura.xml'
        fail_ci_if_error: false

